"""empty message

Revision ID: 6811dac812c5
Revises: 1549dbb431f6
Create Date: 2022-05-03 13:40:29.869173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6811dac812c5'
down_revision = '1549dbb431f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'due')
    # ### end Alembic commands ###
