"""empty message

Revision ID: bc667da91af1
Revises: 2273b58937b7
Create Date: 2022-05-03 17:16:01.365572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc667da91af1'
down_revision = '2273b58937b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('activities', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
